defmodule VokaziWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :vokazi

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_vokazi_key",
    signing_salt: "E58wKUBf",
    same_site: "Lax"
  ]

  socket "/socket", VokaziWeb.UserSocket,
    websocket: true,
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :vokazi,
    gzip: not code_reloading?,
    only: VokaziWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :vokazi
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Origin allowlist lives in config/prod.exs (:cors_plug, :origin) since
  # CORSPlug's init/1 bakes it in at compile time - no origin: override
  # here so it falls through to that config (and to CORSPlug's own sane
  # default header/method list instead of the old wildcard).
  plug CORSPlug

  plug :put_security_headers

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug VokaziWeb.Router

  # This is a JSON API (no HTML views rendered except the OAuth callback
  # redirects, which never echo request-controlled content into a page),
  # so a locked-down `default-src 'none'` CSP is safe here.
  defp put_security_headers(conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("x-content-type-options", "nosniff")
    |> Plug.Conn.put_resp_header("x-frame-options", "DENY")
    |> Plug.Conn.put_resp_header("referrer-policy", "strict-origin-when-cross-origin")
    |> Plug.Conn.put_resp_header("content-security-policy", "default-src 'none'")
  end
end
